// <auto-generated />
namespace AdoNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Employee2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee2));
        
        string IMigrationMetadata.Id
        {
            get { return "202307311635088_Employee2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
