//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegUser
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string updatedby { get; set; }
        public Nullable<short> isactive { get; set; }
        public Nullable<short> ispremium { get; set; }
    }
}
